spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/remote-monitoring
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
